spring:
    profiles:
        active: dev

springdoc:
    api-docs:
        path: /api-docs
gestao:
    jwt:
    secret: gestaoGasto

logging:
    level:
        org:
            hibernate: error
            springframework:
                web: debug
        root: warn
